# Generated by Django 5.1.7 on 2025-03-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("quantity", models.DecimalField(decimal_places=10, max_digits=20)),
                ("trade_time", models.DateTimeField()),
            ],
        ),
    ]
