# Generated by Django 4.2.10 on 2026-08-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('symbol', 'trade_id'), name='unique_symbol_trade'),
        ),
    ]
