services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 crypto_project.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - db

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A crypto_project worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  binance_ws:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py start_binance
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
      - db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    env_file:
        - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A crypto_project flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8100:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - web


volumes:
  pgdata:
